In [17]:
import matplotlib.pyplot as plt
import csv
from textblob import TextBlob #conda install -c conda-forge textblob
import pandas
import sklearn
import _pickle as cPickle
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split 
import pickle
import re

In [2]:
df = pd.read_csv('final_data.csv')

In [3]:
df.head()

,Unnamed: 0,Category,Keyword,Web_Page_URL,Tweet_Website,Author_Name,Author_Web_Page_URL,Tweet_Timestamp,Polarity,Tweet_Content,Tweet_Image_URL,Tweet_Number_of_Likes,Tweet_Number_of_Retweets,Tweet_Number_of_Reviews,Tweet_Number_of_Looks
0,0,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/Tahir_Awan000/status/17151...,Tahir Awan,https://twitter.com/Tahir_Awan000,45218,1,BIG BREAKING: youth of Bahrain just burnt #isr...,https://pbs.twimg.com/ext_tw_video_thumb/17151...,135,56,14,NaN
1,1,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/khankasher1/status/1715109...,PTI خان,https://twitter.com/khankasher1,45218,1,Egyptian Comedian Bassem Youssef on Israel:“It...,https://pbs.twimg.com/ext_tw_video_thumb/17151...,217,91,15,NaN
2,2,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/sickofuzzie/status/1715074...,M Faizan Khan©®,https://twitter.com/sickofuzzie,45218,1,#BREAKING Israel destroyed the largest tower i...,https://pbs.twimg.com/ext_tw_video_thumb/17150...,22,23,7,NaN
3,3,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/sickofuzzie/status/1715071...,M Faizan Khan©®,https://twitter.com/sickofuzzie,45218,1,#BREAKING A super Massive Demonstration in #Pa...,NaN,72,29,9,NaN
4,4,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/abdulrdabboussi/status/171...,Abdul-Rahman,https://twitter.com/abdulrdabboussi,Oct 19Oct 19,?,Umm I think the needed some help to correct th...,https://pbs.twimg.com/media/F81w3nGW8AAbiwi?fo...,1,3,1,NaN

In [4]:
df = df.drop(df[df['Polarity'] == '?'].index)

In [5]:
df.head()

,Unnamed: 0,Category,Keyword,Web_Page_URL,Tweet_Website,Author_Name,Author_Web_Page_URL,Tweet_Timestamp,Polarity,Tweet_Content,Tweet_Image_URL,Tweet_Number_of_Likes,Tweet_Number_of_Retweets,Tweet_Number_of_Reviews,Tweet_Number_of_Looks
0,0,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/Tahir_Awan000/status/17151...,Tahir Awan,https://twitter.com/Tahir_Awan000,45218,1,BIG BREAKING: youth of Bahrain just burnt #isr...,https://pbs.twimg.com/ext_tw_video_thumb/17151...,135,56,14,NaN
1,1,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/khankasher1/status/1715109...,PTI خان,https://twitter.com/khankasher1,45218,1,Egyptian Comedian Bassem Youssef on Israel:“It...,https://pbs.twimg.com/ext_tw_video_thumb/17151...,217,91,15,NaN
2,2,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/sickofuzzie/status/1715074...,M Faizan Khan©®,https://twitter.com/sickofuzzie,45218,1,#BREAKING Israel destroyed the largest tower i...,https://pbs.twimg.com/ext_tw_video_thumb/17150...,22,23,7,NaN
3,3,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/sickofuzzie/status/1715071...,M Faizan Khan©®,https://twitter.com/sickofuzzie,45218,1,#BREAKING A super Massive Demonstration in #Pa...,NaN,72,29,9,NaN
5,5,Top,#IsraelPalestineConflict,https://twitter.com/search?q=%23IsraelPalestin...,https://twitter.com/annvandersteel/status/1715...,Ann Vandersteel,https://twitter.com/annvandersteel,45218,-1,Oh BTW rockets hit the maternity ward of the h...,NaN,52,16,2,NaN

In [6]:
df.groupby('Polarity').describe()

         Unnamed: 0                                                      \
              count        mean         std  min     25%    50%     75%
Polarity
-1            306.0  593.346405  363.250351  5.0  263.50  561.0  869.50
0             334.0  726.272455  387.155811  8.0  391.75  734.0  982.75
1             597.0  637.063652  423.903100  0.0  285.00  591.0  963.00


             max
Polarity
-1        1382.0
0         1437.0
1         1436.0

In [24]:
X = df['Tweet_Content']
y = df['Polarity']

In [25]:
with open('Emoji_Dict.p', 'rb') as emoji_file:
    emoji_dict = pickle.load(emoji_file)

In [26]:
def map_emoji_to_emotion(tweet):
    # Assuming `tweet` is a string containing the tweet text
    # Iterate through each character in the tweet
    for char in tweet:
        # Check if the character is an emoji and exists in the emoji_dict
        if char in emoji_dict:
            # Map the emoji to its corresponding emotion
            emotion = emoji_dict[char]
            print(f"Emoji: {char}, Emotion: {emotion}")

In [27]:
X.apply(map_emoji_to_emotion)

0       None
1       None
2       None
3       None
5       None
        ...
1409    None
1410    None
1411    None
1412    None
1413    None
Name: Tweet_Content, Length: 1413, dtype: object

In [28]:
def split_into_lemmas(content):
    # Remove '@' and '#' symbols
    content = re.sub(r'[@#]', '', content)
    # Convert to lowercase
    content = content.lower()
    # Tokenize and lemmatize
    words = TextBlob(content).words
    return ' '.join([word.lemma for word in words])

X.apply(split_into_lemmas)

0       big breaking youth of bahrain just burnt israe...
1       egyptian comedian bassem youssef on israel “ i...
2       breaking israel destroyed the largest tower in...
3       breaking a super massive demonstration in paki...
5       oh btw rocket hit the maternity ward of the ho...
                              ...
1409    martyr of aqsa from hezbollahpalestine gaza he...
1410    israel arrested a woman who is unable to walks...
1411    a entire world now busy with israel and palest...
1412    a story told in tearsthat 's every individual ...
1413    maya a 6 year old palestinian girl ha to carry...
Name: Tweet_Content, Length: 1413, dtype: object

In [33]:
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(X)

# Create a TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_count)

In [34]:
tfidf_transformer = TfidfTransformer()

content_tfidf = tfidf_transformer.fit_transform(X_tfidf)
print (content_tfidf.shape)

(1413, 6608)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(content_tfidf, y, test_size=0.2, random_state=42)

In [40]:
spam_detector = MultinomialNB().fit(content_tfidf, y_train)

#How many messages does it classify correctly overall?
all_predictions = spam_detector.predict(content_tfidf)
print (all_predictions)

print ('accuracy', accuracy_score(X_train, all_predictions))

ValueError: Input contains NaN